# Generated by Django 6.0.4 on 2026-06-05 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_add_cc_fields'),
        ('ai_agent', '0002_initial'),
        ('loans', '0008_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=10)),
                ('weekly_income', models.DecimalField(decimal_places=2, default=1582.06, help_text='Standard weekly gross pay (full 5-day week)', max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('drafted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_from_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='ai_agent.conversation')),
                ('savings_account', models.ForeignKey(blank=True, help_text='Chase — debt payments and savings go here', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_as_savings', to='accounts.account')),
                ('spending_account', models.ForeignKey(blank=True, help_text='Wells Fargo — weekly spending money stays here', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_as_spending', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-drafted_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategoryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('weekly_limit', models.DecimalField(blank=True, decimal_places=2, help_text='null = no cap (need-basis spending)', max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_limits', to='budget.budget')),
            ],
            options={
                'db_table': 'budget_category_limits',
                'ordering': ['category_name'],
                'unique_together': {('budget', 'category_name')},
            },
        ),
        migrations.CreateModel(
            name='BudgetDebtMonthOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month this override applies to')),
                ('override_type', models.CharField(choices=[('minimum_only', 'Minimum payment only'), ('exact', 'Pay exactly this amount'), ('extra', 'Extra on top of default target'), ('skip', 'Skip this month')], max_length=15)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_overrides', to='budget.budget')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_overrides', to='loans.loan')),
            ],
            options={
                'db_table': 'budget_debt_month_overrides',
                'unique_together': {('budget', 'loan', 'month')},
            },
        ),
        migrations.CreateModel(
            name='BudgetDebtTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(help_text='1 = highest priority')),
                ('monthly_minimum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default_monthly_target', models.DecimalField(decimal_places=2, help_text='Default payment target when no month override exists', max_digits=10)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_targets', to='budget.budget')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_targets', to='loans.loan')),
            ],
            options={
                'db_table': 'budget_debt_targets',
                'ordering': ['priority'],
                'unique_together': {('budget', 'loan')},
            },
        ),
        migrations.CreateModel(
            name='BudgetWeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday of this week')),
                ('week_end', models.DateField(help_text='Sunday of this week')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=10)),
                ('income_expected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transfer_to_savings', models.DecimalField(decimal_places=2, help_text='Move this to Chase (covers debt payments + any savings)', max_digits=10)),
                ('spending_budget', models.DecimalField(decimal_places=2, help_text='Stays in Wells Fargo for living expenses this week', max_digits=10)),
                ('debt_payments', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_plans', to='budget.budget')),
                ('created_from_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week_plans', to='ai_agent.message')),
            ],
            options={
                'db_table': 'budget_week_plans',
                'ordering': ['week_start'],
                'unique_together': {('budget', 'week_start')},
            },
        ),
    ]
