# Generated by Django 6.0.4 on 2026-06-05 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('loans', '0008_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Optimizer', max_length=200)),
                ('weekly_income', models.DecimalField(decimal_places=2, default=1582.06, max_digits=10)),
                ('income_variance_pct', models.DecimalField(decimal_places=2, default=0, help_text='Expected % income reduction for short weeks (e.g. 20 for holiday weeks)', max_digits=5)),
                ('savings_target_pct', models.DecimalField(decimal_places=2, default=0, help_text='Minimum % of monthly income to always save before extra debt payments', max_digits=5)),
                ('strategy', models.CharField(choices=[('avalanche', 'Avalanche — highest APR first (min interest)'), ('snowball', 'Snowball — smallest balance first (fastest wins)')], default='avalanche', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizer_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'optimizer_configs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizerCategoryParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('floor_monthly', models.DecimalField(decimal_places=2, help_text='Minimum you must spend per month — hard constraint', max_digits=10)),
                ('ceiling_monthly', models.DecimalField(decimal_places=2, help_text='Maximum you allow yourself to spend — soft ceiling', max_digits=10)),
                ('is_fixed', models.BooleanField(default=False, help_text='True = floor equals ceiling (e.g. insurance, subscriptions)')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_params', to='budget.optimizerconfig')),
            ],
            options={
                'db_table': 'optimizer_category_params',
                'ordering': ['-floor_monthly'],
                'unique_together': {('config', 'category_name')},
            },
        ),
        migrations.CreateModel(
            name='OptimizerLoanParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('attack', 'Attack — pay as much as possible (avalanche/snowball target)'), ('minimum_only', 'Minimum only — just the required payment'), ('exact', 'Exact amount — pay this specific amount each month'), ('skip', 'Skip — do not include in plan')], default='attack', max_length=15)),
                ('exact_monthly_override', models.DecimalField(blank=True, decimal_places=2, help_text='Required when strategy=exact', max_digits=10, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_params', to='budget.optimizerconfig')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizer_params', to='loans.loan')),
            ],
            options={
                'db_table': 'optimizer_loan_params',
                'unique_together': {('config', 'loan')},
            },
        ),
    ]
