# Generated by Django 6.0.4 on 2026-04-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual Fund'), ('crypto', 'Cryptocurrency'), ('bond', 'Bond'), ('real_estate', 'Real Estate'), ('cash', 'Cash / Money Market'), ('commodity', 'Commodity'), ('other', 'Other')], max_length=20)),
                ('symbol', models.CharField(blank=True, default='', help_text='Ticker or crypto symbol, e.g. AAPL or BTC', max_length=20)),
                ('name', models.CharField(help_text='Human-readable asset name', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('average_cost_basis', models.DecimalField(decimal_places=6, help_text='Average purchase price per unit', max_digits=16)),
                ('current_price', models.DecimalField(decimal_places=6, default=0, help_text='Last fetched market price — updated by price-sync task', max_digits=16)),
                ('price_last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'holdings',
                'ordering': ['asset_type', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='WealthProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='My Projection', max_length=100)),
                ('current_age', models.PositiveSmallIntegerField()),
                ('retirement_age', models.PositiveSmallIntegerField(default=65)),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_return_rate', models.DecimalField(decimal_places=2, help_text='Expected annual return %', max_digits=5)),
                ('target_wealth', models.DecimalField(decimal_places=2, default=1000000, max_digits=16)),
                ('projection_data', models.JSONField(blank=True, default=list)),
                ('years_to_goal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('projected_final_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wealth_projections',
                'ordering': ['-created_at'],
            },
        ),
    ]
