# Generated by Django 6.0.4 on 2026-05-26 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_cc_fields'),
        ('investments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, help_text='Price per unit at time of trade', max_digits=16)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_trades', to='accounts.account')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='investments.holding')),
            ],
            options={
                'db_table': 'investment_trades',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
