# Generated by Django 6.0.4 on 2026-05-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_add_trade_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='average_cost_basis',
            field=models.DecimalField(decimal_places=10, help_text='Average purchase price per unit', max_digits=18),
        ),
        migrations.AlterField(
            model_name='holding',
            name='current_price',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Last fetched market price — updated by price-sync task', max_digits=18),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=10, help_text='Price per unit at time of trade', max_digits=18),
        ),
    ]
