# Generated by Django 6.0.4 on 2026-04-13 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. "Chase Checking"', max_length=255)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('institution', models.CharField(blank=True, default='', max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit (credit card accounts only)', max_digits=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['account_type', 'name'],
            },
        ),
    ]
