# Generated by Django 6.0.4 on 2026-04-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='annual_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='APR as a percentage, e.g. 24.990 (credit cards only)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum monthly payment (credit cards only)', max_digits=12, null=True),
        ),
    ]
