# Generated by Django 6.0.4 on 2026-07-06 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('legs', 'Legs'), ('core', 'Core'), ('cardio', 'Cardio'), ('full_body', 'Full Body'), ('other', 'Other')], default='other', max_length=20)),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.CharField(default='10', max_length=20)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('order', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('body_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('workout_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_water_liters', models.DecimalField(decimal_places=1, default=3.0, max_digits=4)),
                ('daily_calories', models.IntegerField(default=2000)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sets_completed', models.IntegerField(default=0)),
                ('reps_completed', models.CharField(blank=True, max_length=50)),
                ('weight_used', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('completed', models.BooleanField(default=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='fitness.dailylog')),
                ('planned_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.plannedexercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('name', models.CharField(max_length=100)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('user', 'day_of_week')},
            },
        ),
        migrations.AddField(
            model_name='plannedexercise',
            name='workout_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness.workoutday'),
        ),
    ]
