# Generated by Django 6.0.4 on 2026-04-13 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_cc_fields'),
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account this transaction belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.account'),
        ),
    ]
