# Generated by Django 6.0.4 on 2026-04-13 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_add_account_fk'),
        ('transactions', '0003_add_account_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loan',
            field=models.ForeignKey(blank=True, help_text='Friend loan being repaid by this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayment_transactions', to='loans.loan'),
        ),
    ]
