# Generated by Django 6.0.4 on 2026-04-21 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_cc_fields'),
        ('transactions', '0004_add_loan_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, help_text='Destination account for transfers (e.g. credit card being paid)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Source account (or account for income/expense)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.account'),
        ),
    ]
