# Generated by Django 6.0.4 on 2026-05-07 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_initial'),
        ('transactions', '0005_add_to_account_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(blank=True, help_text='Portfolio receiving cash when transaction_type=investment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='investments.portfolio'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('investment', 'Investment')], max_length=10),
        ),
    ]
