# Generated by Django 6.0.4 on 2026-04-12 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('streaming', 'Streaming'), ('music', 'Music'), ('gaming', 'Gaming'), ('software', 'Software / SaaS'), ('phone', 'Phone / Mobile'), ('insurance', 'Insurance'), ('utilities', 'Utilities'), ('fitness', 'Fitness / Gym'), ('news', 'News / Media'), ('education', 'Education'), ('food', 'Food / Delivery'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('yearly', 'Yearly')], default='monthly', max_length=15)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['category', 'name'],
            },
        ),
    ]
