# Generated by Django 6.0.4 on 2026-04-13 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_cc_fields'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account this subscription is charged to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='accounts.account'),
        ),
    ]
