# Generated by Django 6.0.4 on 2026-04-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. "Chase Auto Loan"', max_length=255)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('mortgage', 'Mortgage'), ('auto', 'Auto Loan'), ('student', 'Student Loan'), ('credit_card', 'Credit Card'), ('business', 'Business Loan'), ('other', 'Other')], default='personal', max_length=20)),
                ('lender', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid Off'), ('defaulted', 'Defaulted'), ('refinanced', 'Refinanced')], default='active', max_length=20)),
                ('principal', models.DecimalField(decimal_places=2, help_text='Original loan amount', max_digits=16)),
                ('current_balance', models.DecimalField(decimal_places=2, help_text='Outstanding balance — updated as payments are recorded', max_digits=16)),
                ('annual_interest_rate', models.DecimalField(decimal_places=3, help_text='Annual interest rate as a percentage, e.g. 6.500', max_digits=6)),
                ('term_months', models.PositiveIntegerField(help_text='Original loan duration in months')),
                ('monthly_payment', models.DecimalField(decimal_places=2, help_text='Scheduled minimum monthly payment', max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Calculated or actual payoff date', null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('extra_monthly_payment', models.DecimalField(decimal_places=2, default=0, help_text='Additional amount paid each month beyond minimum', max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=16)),
                ('is_extra_payment', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loan_payments',
                'ordering': ['payment_date'],
            },
        ),
    ]
