# Generated by Django 6.0.4 on 2026-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit (credit cards only)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=3, help_text='Annual interest rate / APR as a percentage, e.g. 24.990', max_digits=6),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original loan amount (not applicable for credit cards)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='term_months',
            field=models.PositiveIntegerField(blank=True, help_text='Original loan duration in months (not applicable for credit cards)', null=True),
        ),
    ]
