# Generated by Django 6.0.4 on 2026-04-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_make_start_date_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment_due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month payment is due, e.g. 2 means due on the 2nd', null=True),
        ),
    ]
