# Generated by Django 6.0.4 on 2026-04-13 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0005_add_payment_due_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('mortgage', 'Mortgage'), ('auto', 'Auto Loan'), ('student', 'Student Loan'), ('credit_card', 'Credit Card'), ('business', 'Business Loan'), ('friend', 'Borrowed from Friend'), ('other', 'Other')], default='personal', max_length=20),
        ),
    ]
