# Generated by Django 6.0.4 on 2026-05-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_add_account_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('mortgage', 'Mortgage'), ('auto', 'Auto Loan'), ('student', 'Student Loan'), ('credit_card', 'Credit Card'), ('business', 'Business Loan'), ('friend', 'Borrowed from Friend'), ('lent_to_friend', 'Lent to Friend'), ('other', 'Other')], default='personal', max_length=20),
        ),
    ]
